"""Fail-closed operating-system isolation primitives."""

from .workspace import (
    WorkspaceBoundaryError,
    WorkspaceConflict,
    WorkspaceConflictReport,
    WorkspaceDiff,
    WorkspaceDiffEntry,
    WorkspaceInspection,
    export_overlay_diff,
    check_workspace_publish_conflicts,
    inspect_workspace,
    snapshot_workspace,
    validate_overlay_candidate,
)
from .launcher import (
    InvalidSandboxRequest,
    IsolationUnavailable,
    SandboxLimits,
    SandboxResult,
    SandboxTerminationReceipt,
    SandboxSession,
    SystemdReadOnlyLauncher,
)
from .landlock import (
    FsAccess,
    LandlockResult,
    LandlockUnavailable,
    PathGrant,
    READ_EXECUTE,
    WORKSPACE_WRITE,
    landlock_abi,
    restrict_current_process,
)
from .workspace_lease import (
    WorkspaceLeaseBusy,
    WorkspaceLeaseError,
    WorkspaceLeaseUnavailable,
    WorkspaceWriteLease,
    acquire_workspace_write_lease,
)
from .workspace_publish import (
    WorkspacePublishAuthorizationLost,
    WorkspacePublishConflict,
    WorkspacePublishError,
    WorkspacePublishReceipt,
    WorkspacePublishRecoveryConflict,
    WorkspacePublicationRecovery,
    publish_workspace_diff,
    recover_workspace_publications,
    recover_workspace_publications_with_outcomes,
)
from .overlay_launcher import (
    OverlayCandidateResult,
    OverlayCandidateSession,
    SystemdOverlayCandidateLauncher,
)
from .provider_sender import (
    ProviderSenderResult,
    SystemdProviderSenderLauncher,
    SystemdProviderSenderSession,
)

__all__ = [
    "InvalidSandboxRequest",
    "IsolationUnavailable",
    "SandboxLimits",
    "SandboxResult",
    "SandboxTerminationReceipt",
    "SandboxSession",
    "SystemdReadOnlyLauncher",
    "SystemdOverlayCandidateLauncher",
    "ProviderSenderResult",
    "SystemdProviderSenderLauncher",
    "SystemdProviderSenderSession",
    "OverlayCandidateResult",
    "OverlayCandidateSession",
    "FsAccess",
    "LandlockResult",
    "LandlockUnavailable",
    "PathGrant",
    "READ_EXECUTE",
    "WORKSPACE_WRITE",
    "WorkspaceBoundaryError",
    "WorkspaceConflict",
    "WorkspaceConflictReport",
    "WorkspaceLeaseBusy",
    "WorkspaceLeaseError",
    "WorkspaceLeaseUnavailable",
    "WorkspacePublishConflict",
    "WorkspacePublishAuthorizationLost",
    "WorkspacePublishError",
    "WorkspacePublishReceipt",
    "WorkspacePublishRecoveryConflict",
    "WorkspacePublicationRecovery",
    "WorkspaceDiff",
    "WorkspaceDiffEntry",
    "WorkspaceInspection",
    "WorkspaceWriteLease",
    "acquire_workspace_write_lease",
    "export_overlay_diff",
    "check_workspace_publish_conflicts",
    "inspect_workspace",
    "publish_workspace_diff",
    "recover_workspace_publications",
    "recover_workspace_publications_with_outcomes",
    "snapshot_workspace",
    "validate_overlay_candidate",
    "landlock_abi",
    "restrict_current_process",
]
