"""Fail-closed operating-system isolation primitives."""

from .workspace import (
    WorkspaceBoundaryError,
    WorkspaceConflict,
    WorkspaceConflictReport,
    WorkspaceDiff,
    WorkspaceDiffEntry,
    WorkspaceInspection,
    export_overlay_diff,
    check_workspace_publish_conflicts,
    inspect_workspace,
    snapshot_workspace,
    validate_overlay_candidate,
)
from .launcher import (
    InvalidSandboxRequest,
    IsolationUnavailable,
    SandboxLimits,
    SandboxResult,
    SandboxSession,
    SystemdReadOnlyLauncher,
)
from .landlock import (
    FsAccess,
    LandlockResult,
    LandlockUnavailable,
    PathGrant,
    READ_EXECUTE,
    WORKSPACE_WRITE,
    landlock_abi,
    restrict_current_process,
)
from .workspace_lease import (
    WorkspaceLeaseBusy,
    WorkspaceLeaseError,
    WorkspaceLeaseUnavailable,
    WorkspaceWriteLease,
    acquire_workspace_write_lease,
)

__all__ = [
    "InvalidSandboxRequest",
    "IsolationUnavailable",
    "SandboxLimits",
    "SandboxResult",
    "SandboxSession",
    "SystemdReadOnlyLauncher",
    "FsAccess",
    "LandlockResult",
    "LandlockUnavailable",
    "PathGrant",
    "READ_EXECUTE",
    "WORKSPACE_WRITE",
    "WorkspaceBoundaryError",
    "WorkspaceConflict",
    "WorkspaceConflictReport",
    "WorkspaceLeaseBusy",
    "WorkspaceLeaseError",
    "WorkspaceLeaseUnavailable",
    "WorkspaceDiff",
    "WorkspaceDiffEntry",
    "WorkspaceInspection",
    "WorkspaceWriteLease",
    "acquire_workspace_write_lease",
    "export_overlay_diff",
    "check_workspace_publish_conflicts",
    "inspect_workspace",
    "snapshot_workspace",
    "validate_overlay_candidate",
    "landlock_abi",
    "restrict_current_process",
]
